import turtle
turtle.shape('turtle')
turtle.color('red')
turtle.down()
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.penup()
turtle.goto(25,0)
turtle.write ("s= 75")
turtle.penup()
turtle.goto(80,35)
turtle.write ("s= 75")

turtle.color("blue")
turtle.pencolor("black")
turtle.begin_fill()    
turtle.pen()
turtle.penup()
turtle.goto(200, -5)
turtle.pendown()
turtle.circle(45)
turtle.left(90)
turtle.forward(45)
turtle.write ("r=45")

d=turtle
d.bgcolor("silver")      
d.color("dark blue")      
d.pencolor("white")  
d.begin_fill()    
d.pen()
d.end_fill()
